### ISSUE TITLE
You can use useLocalStorage hook

### ISSUE THREAD

**Issue by tfarras** [codebjorn/typescript-redux-react#12]
https://github.com/codebjorn/typescript-redux-react/blob/470416879b880ec381daf586b20daf9b08b8f1de/src/helpers/index.ts#L73

https://github.com/streamich/react-use/blob/baa295ddebfab984a9df079ad4c80c5cffa48def/src/useLocalStorage.ts
https://github.com/streamich/react-use/blob/master/docs/useLocalStorage.md

**Comment by codebjorn** [comment]
Okay, I will take a look.
